# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{representations}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["\305\201ukasz Piestrzeniewicz", "Adam Sokolnicki"]
  s.date = %q{2009-10-16}
  s.description = %q{Rails helpers, including form builders are great to allow rapid development of applications and views.  
They are procedural in nature and have hard time to adapt to complex models. They also live in a single namespace making it difficult to find which helpers apply to which models.  
Resource representations change syntax to object oriented and model specific.}
  s.email = %q{skimos00@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE.txt",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "init.rb",
     "lib/representations.rb",
     "lib/view_helpers.rb",
     "rails/init.rb",
     "representations.gemspec",
     "spec/test_application/.gitignore",
     "spec/test_application/Rakefile",
     "spec/test_application/app/controllers/application_controller.rb",
     "spec/test_application/app/controllers/profiles_controller.rb",
     "spec/test_application/app/controllers/users_controller.rb",
     "spec/test_application/app/helpers/application_helper.rb",
     "spec/test_application/app/helpers/profiles_helper.rb",
     "spec/test_application/app/helpers/users_helper.rb",
     "spec/test_application/app/models/profile.rb",
     "spec/test_application/app/models/user.rb",
     "spec/test_application/app/views/users/new.html.erb",
     "spec/test_application/config/boot.rb",
     "spec/test_application/config/database.yml",
     "spec/test_application/config/environment.rb",
     "spec/test_application/config/environments/development.rb",
     "spec/test_application/config/environments/production.rb",
     "spec/test_application/config/environments/test.rb",
     "spec/test_application/config/initializers/backtrace_silencers.rb",
     "spec/test_application/config/initializers/inflections.rb",
     "spec/test_application/config/initializers/mime_types.rb",
     "spec/test_application/config/initializers/new_rails_defaults.rb",
     "spec/test_application/config/initializers/session_store.rb",
     "spec/test_application/config/locales/en.yml",
     "spec/test_application/config/routes.rb",
     "spec/test_application/db/development_structure.sql",
     "spec/test_application/db/migrate/20091009082224_create_users.rb",
     "spec/test_application/db/migrate/20091009082255_create_profiles.rb",
     "spec/test_application/db/migrate/20091013090740_add_created_at_and_updated_at_to_users.rb",
     "spec/test_application/db/migrate/20091014102350_add_charecteristics_to_profile.rb",
     "spec/test_application/db/schema.rb",
     "spec/test_application/db/seeds.rb",
     "spec/test_application/lib/tasks/rspec.rake",
     "spec/test_application/profiles",
     "spec/test_application/profiles.yml",
     "spec/test_application/public/404.html",
     "spec/test_application/public/422.html",
     "spec/test_application/public/500.html",
     "spec/test_application/public/favicon.ico",
     "spec/test_application/public/images/rails.png",
     "spec/test_application/public/index.html",
     "spec/test_application/public/javascripts/application.js",
     "spec/test_application/public/javascripts/controls.js",
     "spec/test_application/public/javascripts/dragdrop.js",
     "spec/test_application/public/javascripts/effects.js",
     "spec/test_application/public/javascripts/prototype.js",
     "spec/test_application/public/robots.txt",
     "spec/test_application/script/about",
     "spec/test_application/script/autospec",
     "spec/test_application/script/console",
     "spec/test_application/script/dbconsole",
     "spec/test_application/script/destroy",
     "spec/test_application/script/generate",
     "spec/test_application/script/performance/benchmarker",
     "spec/test_application/script/performance/profiler",
     "spec/test_application/script/plugin",
     "spec/test_application/script/runner",
     "spec/test_application/script/server",
     "spec/test_application/script/spec",
     "spec/test_application/script/spec_server",
     "spec/test_application/spec/controllers/users_controller_spec.rb",
     "spec/test_application/spec/fixtures/users.yml",
     "spec/test_application/spec/helpers/representations_active_record_r.spec.rb",
     "spec/test_application/spec/helpers/representations_default_r_spec.rb",
     "spec/test_application/spec/helpers/representations_nil_class_r_spec.rb",
     "spec/test_application/spec/helpers/representations_representation_spec.rb",
     "spec/test_application/spec/helpers/representations_spec.rb",
     "spec/test_application/spec/helpers/representations_time_with_zone_r_spec.rb",
     "spec/test_application/spec/helpers/users_helper_spec.rb",
     "spec/test_application/spec/models/user_spec.rb",
     "spec/test_application/spec/rcov.opts",
     "spec/test_application/spec/spec.opts",
     "spec/test_application/spec/spec_helper.rb",
     "spec/test_application/test/functional/profiles_controller_test.rb",
     "spec/test_application/test/unit/helpers/profiles_helper_test.rb"
  ]
  s.homepage = %q{http://github.com/bragi/representations}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Changes syntax of rails helpers and form builders to object oriented and model specific}
  s.test_files = [
    "spec/test_application/lib/representations.rb",
     "spec/test_application/db/schema.rb",
     "spec/test_application/db/migrate/20091009082255_create_profiles.rb",
     "spec/test_application/db/migrate/20091013090740_add_created_at_and_updated_at_to_users.rb",
     "spec/test_application/db/migrate/20091009082224_create_users.rb",
     "spec/test_application/db/migrate/20091014102350_add_charecteristics_to_profile.rb",
     "spec/test_application/db/seeds.rb",
     "spec/test_application/spec/helpers/users_helper_spec.rb",
     "spec/test_application/spec/helpers/representations_default_r_spec.rb",
     "spec/test_application/spec/helpers/representations_representation_spec.rb",
     "spec/test_application/spec/helpers/representations_nil_class_r_spec.rb",
     "spec/test_application/spec/helpers/representations_spec.rb",
     "spec/test_application/spec/helpers/representations_time_with_zone_r_spec.rb",
     "spec/test_application/spec/helpers/representations_active_record_r.spec.rb",
     "spec/test_application/spec/controllers/users_controller_spec.rb",
     "spec/test_application/spec/models/user_spec.rb",
     "spec/test_application/spec/spec_helper.rb",
     "spec/test_application/app/helpers/application_helper.rb",
     "spec/test_application/app/helpers/profiles_helper.rb",
     "spec/test_application/app/helpers/users_helper.rb",
     "spec/test_application/app/controllers/profiles_controller.rb",
     "spec/test_application/app/controllers/application_controller.rb",
     "spec/test_application/app/controllers/users_controller.rb",
     "spec/test_application/app/models/user.rb",
     "spec/test_application/app/models/profile.rb",
     "spec/test_application/test/unit/helpers/profiles_helper_test.rb",
     "spec/test_application/test/functional/profiles_controller_test.rb",
     "spec/test_application/config/environments/production.rb",
     "spec/test_application/config/environments/test.rb",
     "spec/test_application/config/environments/development.rb",
     "spec/test_application/config/routes.rb",
     "spec/test_application/config/boot.rb",
     "spec/test_application/config/initializers/session_store.rb",
     "spec/test_application/config/initializers/mime_types.rb",
     "spec/test_application/config/initializers/backtrace_silencers.rb",
     "spec/test_application/config/initializers/inflections.rb",
     "spec/test_application/config/initializers/new_rails_defaults.rb",
     "spec/test_application/config/environment.rb",
     "spec/representations_default_r_spec.rb",
     "spec/representations_representation_spec.rb",
     "spec/representations_nil_class_r_spec.rb",
     "spec/representations_spec.rb",
     "spec/representations_time_with_zone_r_spec.rb",
     "spec/representations_active_record_r.spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
