Feature: Test  profile forms generated by Representations
  In order to create a profile
  I want to have a valid html form

  Scenario: creating a new profile
    Given I'am on the new profile page
    And I fill some values into form
    And maried value is checked
    When I press ok
    Then I should have a new profile with maried value set to true
  
  
