Feature: Test  profile forms generated by Representations
  In order to create a profile
  I want to have a valid html form

  Scenario: creating a new profile
    Given I am on the new profile page
    When I press "ok"


  
  
