Feature: Test  profile forms generated by Representations
  In order to create a profile
  I want to have a valid html form

  Scenario: creating a new profile
    Given I am on the new profile page
    And I attach the file "public/images/rails.png" to "profile_picture"
    When I press "ok"


  
  
